### ISSUE TITLE
A circular dependency is detected for bundle 'frontend\assets\AppAsset

### ISSUE THREAD

**Issue by vladmeh** [rmrevin/yii2-fontawesome#12]
Доброго времени суток.
В шаблоне "yii2-app-advanced" при подключении через
```php
class AppAsset extends AssetBundle
{
    // ...

    public $depends = [
        // ...
        '\rmrevin\yii\fontawesome\AssetBundle'
    ];
}
```
php 5.4.43, выдает ошибку
` An Error occurred while handling another error:
exception 'yii\base\InvalidConfigException' with message 'A circular dependency is detected for bundle 'frontend\assets\AppAsset'.' in /var/www/.../vendor/yiisoft/yii2/web/View.php:293 `
Я так подозреваю, что лечится переименованием класса `AssetBundle` в (например) `FontAwesomeBundle` что бы не было `Циклических зависимостей в пространстве имен`

Пользуюсь `CDNAssetBundle`...

**Comment by rmrevin** [comment]
Нет. Эта ошибка свидетельствет о том, что Вы подключаете зацикленную зависимость. То есть два каких-то бандла подключают друг друга у себя в `depends`. Только что проверил, на чистом `yii2-app-advanced` бандл подключается без проблем.

**Comment by vladmeh** [comment]
Да у меня то-же проект пока еще чистый (почти)
в AppAsset подключен только yii2-materialize от [wiisoft](https://github.com/wiisoft/yii2-materialize)
```php
<?php
namespace frontend\assets;

use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/screen.css',
    ];
    public $js = [
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'wii\materialize\MaterializeAsset',
        '\rmrevin\yii\fontawesome\AssetBundle'
    ];
}
```
Вполне возможно что-то с ним не так, надо разбираться, но
```php
public $depends = [
        'yii\web\YiiAsset',
        'wii\materialize\MaterializeAsset',
        '\rmrevin\yii\fontawesome\AssetBundle'
    ];
```
Выдает ошибку, а 
```php
public $depends = [
        'yii\web\YiiAsset',
        'wii\materialize\MaterializeAsset',
        //'\rmrevin\yii\fontawesome\AssetBundle'
    ];
```
и 
```php
public $depends = [
        'yii\web\YiiAsset',
        'wii\materialize\MaterializeAsset',
        '\rmrevin\yii\fontawesome\CDNAssetBundle'
    ];
```
работает. 

А самое интересное что ошибка вылезает только на удаленном хосте, на локальном сервере все работает прекрасно.

**Comment by rmrevin** [comment]
Какая версия пхп на хосте? Попробуйте убрать слеш перед rmrrevin, возможно автолоадер как-то  нанего реагирует. Вообще он не должен ругаться. Автолоадер используете от composer'a?

**Comment by vladmeh** [comment]
Да, Вы правы. Я идиот, естественно нужно подключить
```php
composer global require "fxp/composer-asset-plugin:~1.0.3"
```
На локальном сервере он подключен глобально, а на удаленном - его нужно подключать вручную.
Все заработало. Отличное приложение.

Спасибо за консультацию.

**Comment by rmrevin** [comment]
Рад, что Вы разобрались. Пакет `fxp/composer-asset-plugin` вообще приносит много боли. Core team обещали его выпилить в следующем году.
