### ISSUE TITLE
Font-awesome download two times

### ISSUE THREAD

**Issue by phpyii** [rmrevin/yii2-fontawesome#15]
https://github.com/rmrevin/yii2-fontawesome/blob/master/composer.json#L29  
Some extensions are used in font-awesome.  as follows:
"font-awesome": ">=4.1.0"  

Finally installed a font-awesome and fontawesome  
It is recommended that the name agree with this  
https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json

**Comment by lanbiaowan** [comment]
有道理

**Comment by rmrevin** [comment]
Update plugin `fxp/composer-asset-plugin` to version `1.1.1`.
In this version, only one directory `fontawesome`
