### ISSUE TITLE
composer crushes -  Invalid version string "v4.1.*"

### ISSUE THREAD

**Issue by spi7fire** [rmrevin/yii2-fontawesome#16]
[RuntimeException]
  Could not load package rmrevin/yii2-fontawesome in http://packagist.org: [UnexpectedValueException] Could
  not parse version constraint v4.1.*: Invalid version string "v4.1.*"

  [UnexpectedValueException]
  Could not parse version constraint v4.1.*: Invalid version string "v4.1.*"

**Comment by rmrevin** [comment]
Versions of extension `rmrevin/yii2-fontawesome` are not versions of the font.
Lastes version of `rmrevin/yii2-fontawesome` is `2.13.0`

**Comment by achertovsky** [comment]
Совет не о чем.
Попробуй сделать апдейт и увидишь ту же ошибку у себя. плюсую топик стартеру.

**Comment by rmrevin** [comment]
@achertovsky 
вопрос ни о чём.
У моего расширения нет версии `v4.1.`
Композер ясно об этом говорит.

**Comment by achertovsky** [comment]
в композере указана версия ~2.11

**Comment by achertovsky** [comment]
@rmrevin 
http://screencloud.net/v/3kfK

**Comment by spi7fire** [comment]
error received when trying to update composer with fontawesome, it is looking for fontawesome 4.1.* version:

/.composer/cache/repo/https---packagist.org/provider-rmrevin$yii2-fontawesome.json from cache



  [RuntimeException]
  Could not load package rmrevin/yii2-fontawesome in http://packagist.org: [UnexpectedValueException] Could not parse version constraint v4.1.*: Invalid version stri
  ng "v4.1.*"

**Comment by rmrevin** [comment]
@spi7fire @achertovsky 
You do `composer update` or `composer install`?

**Comment by achertovsky** [comment]
@rmrevin 
same result for install and update.

**Comment by rmrevin** [comment]
Version `v4.1.*` is version of fontawesome in extension version `1.2.0` (old version) https://github.com/rmrevin/yii2-fontawesome/releases/tag/1.2.0.
Since then expansion has came to use bower package.
And for some reason the developers was renamed this release.
http://i.imgur.com/FNp0dBA.png (version 4.1.0 without `v`)
Just checked, the package is installed without problems.
Try to remove and reinstall the package.
`composer require rmrevin/yii2-fontawesome --prefer-dist`
```
Using version ^2.13 for rmrevin/yii2-fontawesome       
./composer.json has been updated                                         
Updating dependencies (including require-dev)           
  - Installing bower-asset/fontawesome (v4.5.0)            
    Loading from cache

  - Installing rmrevin/yii2-fontawesome (2.13.0)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by rmrevin** [comment]
Developers make two tags `4.1.0` and `v4.1.0` http://i.imgur.com/uGrIZyw.png
Packagist apparently later changed his tag to a fresh or merged two versions.

**Comment by achertovsky** [comment]
@rmrevin 
so u want to tell that this bug is temporary?

**Comment by rmrevin** [comment]
No, not temporary. At the time of release `1.2.0` of this god it was not.
If you want to use a branch `1.*`, you must install version `1.2.1`. There's this bug is fixed.
https://github.com/rmrevin/yii2-fontawesome/releases/tag/1.2.1

**Comment by achertovsky** [comment]
@rmrevin 
http://screencloud.net/v/knTB

**Comment by rmrevin** [comment]
Obviously, you composer establishes an older version.
Try to update composer, update the plugin `fxp/composer-asset-plugin` and clear the cache composer. 
And repeat the installation.

**Comment by achertovsky** [comment]
@rmrevin 
looks like cache. ty for u'r time!

**Comment by rmrevin** [comment]
I'm glad I could help.
Can you put a star to this extension.

**Comment by achertovsky** [comment]
@rmrevin 
done

**Comment by rmrevin** [comment]
Thanks!
