### ISSUE TITLE
error Invalid Parameter – yii\base\InvalidParamException

### ISSUE THREAD

**Issue by ofilin86** [rmrevin/yii2-fontawesome#17]
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: <path>\vendor\bower/fontawesome

change in \vendor\rmrevin\yii2-fontawesome\AssetBundle.php row 20
from
public $sourcePath = '@bower/fontawesome';
on
public $sourcePath = '@bower/bower-asset/fontawesome';

**Comment by rmrevin** [comment]
Update `fxp/composer-asset-plugin` to version `1.1.1` and reinstall composer packages.

**Comment by ofilin86** [comment]
и так и так работает, но последний вариант правильней...
спасибо :)

**Comment by rmrevin** [comment]
I'm glad I could help)
