### ISSUE TITLE
require "fortawesome/font-awesome": "~4.7"

### ISSUE THREAD

**Issue by loveorigami** [rmrevin/yii2-fontawesome#26]
Зачем грузить библиотеку дважды?
тут
* https://github.com/rmrevin/yii2-fontawesome/blob/master/composer.json#L28

и тут
* https://github.com/rmrevin/yii2-fontawesome/blob/master/assets/css/font-awesome.css

или это переходной релиз?

**Comment by rmrevin** [comment]
@loveorigami директория assets теперь deprecated и в будущем будет удалена
