### ISSUE TITLE
Php 5.5

### ISSUE THREAD

**Issue by julianrutten** [rmrevin/yii2-fontawesome#27]
https://github.com/rmrevin/yii2-fontawesome/blob/master/composer.json#L26

Do you need php 5.5 for this project? Since its merely an asset wouldnt 5.4 suffice (yii2 is compatible with it as well).

**Comment by rmrevin** [comment]
We are planning a new version for php 7. So would gradually increase the minimum requirements. Rollback in extension version `2.17.1`.

P.s. PHP Versions below 5.6 are no longer supported, it is better to upgrade.

**Comment by julianrutten** [comment]
That is true but why not support 5.4 as well? Yii2 does the same? Why not just use a different version for your PHP 7 dependency, so at least people can use this repo with a static semver instead of having to fork it.
