### ISSUE TITLE
Latest release not marked as latest release

### ISSUE THREAD

**Issue by derekisbusy** [rmrevin/yii2-fontawesome#28]
In https://github.com/rmrevin/yii2-fontawesome/releases the latest release is marked as 2.15.0 but there are several newer releases since then. In composer if you require something like ~2.9 it gets 2.15 instead of 2.17.1. Why is 2.15.0 marked as the latest release instead of 2.17.1?

**Comment by rmrevin** [comment]
Hello. Added release 2.16 and 2.17. Thanks for issue.
