### ISSUE TITLE
Class 'FAR' not found

### ISSUE THREAD

**Issue by gb5256** [rmrevin/yii2-fontawesome#34]
Hi, 
just intstalled this exentsion. 
But I get an error:
"Class FAR not found".

can it be that this is wrong (coming from your exmaples):
use rmrevin\yii\fontawesome\FA;

Should this be:
use rmrevin\yii\fontawesome\FAR; ?

This would not throw the error anymore, but does not show an icon but a broken character.

thanks,
gb5256

**Comment by rmrevin** [comment]
Yes, in readme error. It should be `use rmrevin\yii\fontawesome\FAR;`.
Show composer.json, the list of the asset bundles that are connected on the page (you can see in the yii2 debug panel) and how you call the icon in the template.

**Comment by rmrevin** [comment]
Fixed readme. Thanks.
