### ISSUE TITLE
fonts are not loaded via asset

### ISSUE THREAD

**Issue by alexgivi** [rmrevin/yii2-fontawesome#35]
AssetBundle only adds css to result page. Fonts are not loaded, so icons doesn't work.
one way to avoid this problem - is to copy fonts to web dir, and make own css with fonts description.
Yii2 doesn't allow publish any files except css and js via assets mechanism, so, it's necessary to find a way to publish this files.

**Comment by mirkhamidov** [comment]
is possible to solve this?

**Comment by rmrevin** [comment]
@alexgivi @mirkhamidov show your app configuration

**Comment by mirkhamidov** [comment]
@rmrevin I just added as dependency to main AppAaset

**Comment by rmrevin** [comment]
@mirkhamidov  Good. But I do not know how your assets are published. Open the debug panel of your browser and see where the font files are trying to load. If the location is incorrect, try to find the cause in the configuration of your web directory and assetManager component.

**Comment by alexgivi** [comment]
![2018-05-10 18-11-35](https://user-images.githubusercontent.com/6298299/39877091-a3242e4e-547d-11e8-828f-7e1679ebda9e.png)
font is loaded by browser, but on page i see
![2018-05-10 18-12-49](https://user-images.githubusercontent.com/6298299/39877145-c9dee6f0-547d-11e8-802f-037e012a9725.png)
maybe it's wrong font files... why don't you use https://github.com/FortAwesome/Font-Awesome repo as required dependency of your repo?

**Comment by alexgivi** [comment]
interesting, that FAS is working correct. FAR and FAL - icons doesn't show.

**Comment by javiulacia** [comment]
@alexgivi @mirkhamidov , guys you are probably mixing CSS rules. Be sure not to duplicate Fontawesome in your old style sheets. @rmrevin vendor works fine for me.

**Comment by rmrevin** [comment]
Can't reproduce bug.
