### ISSUE TITLE
What about FontAwesomePro?

### ISSUE THREAD

**Issue by gb5256** [rmrevin/yii2-fontawesome#39]
HI,
just curious...
If I buy a license for the Pro Version of the font, what would be the workflow then?
Would this be supported somehow?

Thanks.

**Comment by javiulacia** [comment]
You could customize/override AssetBundles -> https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#customizing-asset-bundles

**Comment by rmrevin** [comment]
Hi. Try to use version 3.2. In readme describes different ways to connect a font.
