### ISSUE TITLE
Nor all size accepted in size() method (like fa-xs, fa-10x)

### ISSUE THREAD

**Issue by sanyisasha** [rmrevin/yii2-fontawesome#44]
There is fa-xs, fa-sm, fa-7x, fa-10x but size() method throw error:  
FontAwesome::size() - invalid value. Use one of the constants: FontAwesome::SIZE_LARGE, FontAwesome::SIZE_2X, FontAwesome::SIZE_3X, FontAwesome::SIZE_4X, FontAwesome::SIZE_5X.

**Comment by rmrevin** [comment]
Sizes added in `3.3.0` version. Thanks for issue.
