### ISSUE TITLE
Released version 3.3.0 does not provide FontAwesome 5.7.1

### ISSUE THREAD

**Issue by f1amy** [rmrevin/yii2-fontawesome#47]
The change log says "Font Awesome updated to version 5.7.1" but if we look at [**this file**](https://github.com/rmrevin/yii2-fontawesome/blob/3.3.0/CdnFreeAssetBundle.php#L20) (from tag 3.3.0), then this is actually version 5.3.1.
Please fix this so that I can use some of the new icons added in this release.
Also version 3.3.0 is not marked as the latest version.

**Comment by f1amy** [comment]
sorry for #48 and #49, I'm learning git/github

**Comment by rmrevin** [comment]
Thank you for message. Indeed, I forgot to fix it in cdn bundle.
