### ISSUE TITLE
Invalid Parameter – yii\base\InvalidParamException

### ISSUE THREAD

**Issue by TmorezT** [rmrevin/yii2-fontawesome#53]
I'm getting this error when I'm trying to approve a user in dashboard, kindly help.

![FireShot Capture 020 - Invalid Parameter – yii_base_InvalidParamException - localhost](https://user-images.githubusercontent.com/53572706/63157067-ca792680-c01e-11e9-8eae-9a3f4e8e3b6b.png)

**Comment by rmrevin** [comment]
The problem is not related to the extension. Look for a mistake in business logic. Most likely you enter the wrong access credentials.

**Comment by TmorezT** [comment]
> The problem is not related to the extension. Look for a mistake in business logic. Most likely you enter the wrong access credentials.

I did not understand by "Look for a mistake in business logic"

**Comment by rmrevin** [comment]
This means that the error is in the logic of your application, and not in the extension or framework. We cannot help with the errors of your application.
