### ISSUE TITLE
Release 3.5.0 not tagged (so not available)

### ISSUE THREAD

**Issue by kmindi** [rmrevin/yii2-fontawesome#56]

**Comment by rmrevin** [comment]
We apologize for any inconvenience caused. The tag is affixed. Also added version 3.6.0 with a new version of the font.

**Comment by kmindi** [comment]
Thankyou, yet is is not available in packagist. Also the information there states that "This package is not auto-updated." (https://packagist.org/packages/rmrevin/yii2-fontawesome). Maybe you could set up the described webhook so everytime you create/push a new tag, also packagist is updated https://packagist.org/about#how-to-update-packages (I can open a separate issue if you want)

**Comment by rmrevin** [comment]
Thanks, I installed a webhook, the versions in packagist have been updated. Previously, everything was updated, apparently the mechanism changed.
